### PR TITLE
Update all.SHA256SUMS

### PR DESCRIPTION
**Pull request by 256dummy**

### CODE REVIEW

**Comment by willcl-ark** [comment]
Great success? 😆

**Comment by 0xB10C** [comment]
But why does the job fail?

**Comment by willcl-ark** [comment]
It seemed more useful to have it fail on a mismatch? Do you think not?

I was thinking that it's off for CI to go green, if it should fail?

**Comment by 0xB10C** [comment]
Some prior discussion here: https://github.com/bitcoin-core/guix.sigs/issues/1203#issuecomment-2073799809

**Comment by willcl-ark** [comment]
OK, will make another change and squash for `v.final-final-final-final`

**Comment by 0xB10C** [comment]
I guess it can be failing and signaling-only at the same time. But I'm not sure if  that's consensus.

**Pull request closed without merging**
